<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2LONNQF" ignored="1" name="Parallel Run-Chrome" tests="1" failures="1" timestamp="16 Aug 2020 18:15:24 GMT" time="50.536" errors="0">
  <testcase name="LoginCheck" time="33.821" classname="com.qa.TestClass.TestClass">
    <failure type="java.lang.AssertionError" message="expected [ContactsNew] but found [Loading...]">
      <![CDATA[java.lang.AssertionError: expected [ContactsNew] but found [Loading...]
at com.qa.TestClass.TestClass.LoginCheck(TestClass.java:78)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- LoginCheck -->
  <testcase name="invalidDataLogin" time="0.0" classname="com.qa.TestClass.TestClass">
    <ignored/>
  </testcase> <!-- invalidDataLogin -->
</testsuite> <!-- Parallel Run-Chrome -->
